### ISSUE TITLE
TS2345 error when injecting InjectableRxStompConfig into RxStomp.stompClient.configure

### ISSUE THREAD

**Issue by GutsFun** [stomp-js/rx-stomp#207]
Since the last week I have this error at runtime (sorry it's in French) : 

```bash
L'argument de type 'InjectableRxStompConfig' n'est pas attribuable au paramètre de type 'StompConfig'.
  Les types de la propriété 'beforeConnect' sont incompatibles.
    Impossible d'assigner le type '(client: RxStomp) => void | Promise<void>' au type '() => void | Promise<void>'.ts(2345)`
```
As a workaround I override the `InjectableRxStompConfig` with a custom `StompConfig` : 
```typescript
import { InjectableRxStompConfig } from '@stomp/ng2-stompjs';

export class FixedStompConfig extends InjectableRxStompConfig {
  constructor() {
    super();
  }
  beforeConnect?: () => void | Promise<void>;
}
```
Any idea why this is appear like a sudden ? My Angular-cli version have not changed and is 7.3.10

**Comment by kum-deepak** [comment]
I think it was caused by https://github.com/stomp-js/rx-stomp/commit/1adf2d36eb1f74b959606396a58763218bb6dde5 in order to fix https://github.com/stomp-js/rx-stomp/issues/204. I made changes expecting it to be backward compatible, but looks like it was not.

The version 0.3.5 was released few days ago.
